# Generated by Django 5.1.1 on 2024-09-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('stock_quantity', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
